### ISSUE TITLE
Could I update the document to be Python 3 focused?

### ISSUE THREAD

**Issue by alexr-plutoflume** [JeffPaine/beautiful_idiomatic_python#3]
I enjoyed your document.

Now that Python 2 is about to go unsupported, do you think it's an appropriate time to put the Python 3 content first, or even remove the Python 2 content completely? If I were to find some free time to do so, would you consider accepting those changes?

**Comment by JeffPaine** [comment]
Hello! Sorry for the (very) long delay, as I somehow missed this issue.

I think after some reflection I'd prefer to leave this as a read-only archive rather than modify it to python 3. I agree py3 is the future and this py2 doc is the past. Perhaps one day Raymond will give a similar talk for python 3 :)
